== TODO

* Finish emoji parsing
* Finish JSON data storage
* Add data storage rotation
* Add exception handling for broken internet connection (IOError from owm api)
** urlopen error
+
----
Traceback (most recent call last):
  File "tempi-script.py", line 138, in <module>
    perform_update()
  File "tempi-script.py", line 123, in perform_update
    get_outside()
  File "tempi-script.py", line 56, in get_outside
    observation = owm.weather_at_zip_code(zip_code,country_code)
  File "/usr/local/lib/python2.7/dist-packages/pyowm/webapi25/owm25.py", line 282, in weather_at_zip_code
    'lang': self._language})
  File "/usr/local/lib/python2.7/dist-packages/pyowm/commons/weather_client.py", line 94, in call_API
    return self._lookup_cache_or_invoke_API(self._cache, url, timeout)
  File "/usr/local/lib/python2.7/dist-packages/pyowm/commons/weather_client.py", line 65, in _lookup_cache_or_invoke_API
    raise api_call_error.APICallError(str(e), e)
pyowm.exceptions.api_call_error.APICallError: Exception in calling OWM web API.
Reason: <urlopen error [Errno -2] Name or service not known>
Caused by: <urlopen error [Errno -2] Name or service not known>
----
** IOError



== DONE
